# nixpacks.toml

[phases.setup]
nixpkgs = ["nodejs", "python310"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd fast_api_backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[phases.start]
cmds = [
  "cd fast_api_backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
]
